import os
from os import path
from collections import OrderedDict
import sys

from snakemake.utils import min_version

min_version("8.10.7")


configfile: "config/config.yml"


include: "rules/commons.smk"
include: "rules/qc.smk"
include: "rules/utils.smk"
include: "rules/datamod.smk"
include: "rules/alignment.smk"
include: "rules/alignmod.smk"
include: "rules/quantification.smk"
include: "rules/diffexp.smk"


inputdir = config["inputdir"]


rule all:
    input:
        rule_all_input(),
